app = 'abstractos'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

[[vm]]
  size = 'performance-4x'
